
title: Afterburn
email: hello@nebbiatech.com
description: >- # this means to ignore newlines until "baseurl:"
  Afterburn makes you fly!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

## => Build
##############################
timezone: America/New_York

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  
## => Analytics
##############################
google_analytics:   #UA-********-*
google_verify:      #*********************************-****
bing_verify: # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here

sass:
  sass_dir: _sass
  style: compressed

include: 
- .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-menus
  - jekyll-redirect-from
  - jemoji